sudo: required

language: minimal

services: docker

before_install:
  - docker -v

install:
  - travis_retry docker-compose pull
  - docker build -t digirati/nlw-madoc .

before_script:
  - docker-compose up
  - ./.travis/wait-for-omeka.sh

script:
  - .travis/test-script.sh

after_script:
  - docker-compose down

cache:
  bundler: true
  directories:
    - $HOME/docker

if: |
  branch = master OR \
  type = pull_request
